name: CI & Deploy

on:[workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # # 4. 代码检查
      # - name: Run lint
      #   run: npm run lint

      # # 5. 单元测试
      # - name: Run tests
      #   run: npm test

      # 6. 构建项目
      - name: Build the app
        run: npm run build

      # 7. 通过 SSH 部署到服务器
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 设置项目路径
            PROJECT_DIR=/home/myproject
            # 设置构建产物部署路径（Nginx root 对应）
            PUBLIC_DIR=/home/project

            # 创建目录（如不存在）
            [ ! -d "$PROJECT_DIR" ] && mkdir -p "$PROJECT_DIR"
            [ ! -d "$PUBLIC_DIR" ] && mkdir -p "$PUBLIC_DIR"

            # 进入项目目录
            cd "$PROJECT_DIR"

            # 如果是 Git 仓库就 pull
            if [ -d ".git" ]; then
              echo "[INFO] Git repo exists, pulling latest code..."
              git pull origin main
            else
              # 不是 Git 仓库？先清空再 clone！
              echo "[INFO] Not a Git repo. Resetting and cloning..."
              rm -rf "$PROJECT_DIR"/*
              git clone https://github.com/micheal-du/vite-project.git "$PROJECT_DIR"
            fi

            # 安装依赖并构建
            npm install
            npm run build

            # 拷贝到 Nginx 部署目录
            cp -r dist/* "$PUBLIC_DIR"


