name: Deploy Static Site via Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: micheal-du/git-workflow-kit/.github/workflows/deploy-test.yml@master
    with:
      build_command: npm run build:test
      target_path: /home/projectA
    secrets:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}