name: CI & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # # 4. 代码检查
      # - name: Run lint
      #   run: npm run lint

      # # 5. 单元测试
      # - name: Run tests
      #   run: npm test

      # 6. 构建项目
      - name: Build the app
        run: npm run build

      # 7. 通过 SSH 部署到服务器
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd home/myproject
            git pull origin main
            npm install
            npm run build
            pm2 restart app

