name: Deploy Static Site to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: micheal-du/git-workflow-kit/.github/workflows/reusable-deploy-with-symlink.yml@main
    with:
      build_command: npm run build:prod
      deploy_base: /opt/myproject
    secrets:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}