name: Deploy Static Site to Production With Symlink

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: micheal-du/git-workflow-kit/.github/workflows/reusable-deploy-with-symlink.yml@master
    with:
      build_command: npm run build:prod
      deploy_base: ${{ env.HOME }}/myproject
    secrets:
      SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
      SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.PROD_SERVER_SSH_KEY }}