name: Deploy Static Site to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: micheal-du/git-workflow-kit/.github/workflows/reusable-deploy-prod.yml@master
    with:
      build_command: npm run build:prod
      target_path: /home/your-project-prod
    secrets:
      SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
      SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.PROD_SERVER_SSH_KEY }}
