name: SSH Test

on: [workflow_dispatch]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Try SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "连接成功"
            uname -a
